const MOCK_USERS = [
  { id: 1, name: "Ali Yilmaz", email: "ali@metu.edu.tr", role: "engineer", institution: "METU", expertise: "Medical Imaging AI", city: "Ankara", is_suspended: false },
  { id: 2, name: "Selin Kaya", email: "selin@hacettepe.edu.tr", role: "engineer", institution: "Hacettepe", expertise: "Embedded Systems", city: "Ankara", is_suspended: false },
  { id: 3, name: "Dr. Mehmet Oz", email: "m.oz@istanbul.edu.tr", role: "doctor", institution: "Istanbul University Hospital", expertise: "Cardiology", city: "Istanbul", is_suspended: false },
  { id: 4, name: "Dr. Ayse Demir", email: "a.demir@ege.edu.tr", role: "doctor", institution: "Ege University Hospital", expertise: "Oncology", city: "Izmir", is_suspended: false },
  { id: 5, name: "Admin User", email: "admin@healthai.edu", role: "admin", institution: "HealthAI Platform", expertise: "-", city: "-", is_suspended: false },
];

const MOCK_POSTS = [
  {
    id: 1,
    user_id: 1,
    title: "AI-Powered ECG Analysis Tool",
    domain: "Cardiology",
    role_type: "engineer",
    stage: "prototype",
    status: "active",
    explanation: "We have developed an LSTM-based model for arrhythmia detection from ECG signals.",
    expertise_needed: "Cardiologist with ECG interpretation experience",
    confidentiality: "public",
    expiry_date: "2026-06-01",
    city: "Ankara",
    country: "Turkey",
    auto_close: true,
    created_at: "2026-03-15"
  },
  {
    id: 2,
    user_id: 3,
    title: "Remote Patient Monitoring for Heart Failure",
    domain: "Cardiology",
    role_type: "doctor",
    stage: "idea",
    status: "active",
    explanation: "Need an engineer to scope feasibility.",
    expertise_needed: "IoT / wearable sensor engineer with ML background",
    confidentiality: "meeting_only",
    expiry_date: "2026-05-15",
    city: "Istanbul",
    country: "Turkey",
    auto_close: false,
    created_at: "2026-03-20"
  },
  {
    id: 3,
    user_id: 2,
    title: "Smart Insulin Delivery Algorithm",
    domain: "Endocrinology",
    role_type: "engineer",
    stage: "concept_validation",
    status: "meeting_scheduled",
    explanation: "Need an endocrinologist to validate the model.",
    expertise_needed: "Endocrinologist specializing in diabetes management",
    confidentiality: "public",
    expiry_date: "2026-07-01",
    city: "Ankara",
    country: "Turkey",
    auto_close: false,
    created_at: "2026-04-01"
  },
  {
    id: 4,
    user_id: 4,
    title: "Breast Cancer Screening Assistance Tool",
    domain: "Oncology",
    role_type: "doctor",
    stage: "pilot_testing",
    status: "partner_found",
    explanation: "The engineering partner has been found.",
    expertise_needed: "Computer vision engineer",
    confidentiality: "meeting_only",
    expiry_date: "2026-05-01",
    city: "Izmir",
    country: "Turkey",
    auto_close: true,
    created_at: "2026-02-10"
  },
  {
    id: 5,
    user_id: 1,
    title: "Retinal Disease Detection via Fundus Images",
    domain: "Ophthalmology",
    role_type: "engineer",
    stage: "idea",
    status: "draft",
    explanation: "Draft post - not yet published.",
    expertise_needed: "Ophthalmologist",
    confidentiality: "public",
    expiry_date: "2026-08-01",
    city: "Ankara",
    country: "Turkey",
    auto_close: false,
    created_at: "2026-04-10"
  }
];

const MOCK_ACTIVITY_LOGS = [
  { id: 1, user_id: 1, action: "POST_CREATED", target_type: "post", target_id: 1, timestamp: "2026-03-15 09:12" },
  { id: 2, user_id: 3, action: "USER_LOGIN", target_type: "user", target_id: 3, timestamp: "2026-03-20 11:30" },
  { id: 3, user_id: 3, action: "POST_CREATED", target_type: "post", target_id: 2, timestamp: "2026-03-20 11:45" },
  { id: 4, user_id: 2, action: "POST_CREATED", target_type: "post", target_id: 3, timestamp: "2026-04-01 08:00" },
  { id: 5, user_id: 3, action: "MEETING_REQUEST", target_type: "meeting_request", target_id: 1, timestamp: "2026-04-05 14:20" },
  { id: 6, user_id: 2, action: "MEETING_CONFIRMED", target_type: "meeting_request", target_id: 1, timestamp: "2026-04-06 09:00" },
];